name: Automate Preprocessing

on:
  push:
    branches:
      - main

jobs:
  preprocessing-job:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode dari repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install Library dari requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Jalankan Script Preprocessing
    - name: Run Preprocessing Script
      run: |
        cd preprocessing
        python automate_preprocessing.py

    # 5. Simpan Hasil Data Bersih sebagai Artifact
    - name: Upload Processed Data
      uses: actions/upload-artifact@v4
      with:
        name: cleaned-dataset
        path: preprocessing/data_processed/
        retention-days: 5